"""Make image_url nullable

Revision ID: 0c981dc7c9f7
Revises: 8e26edfca115
Create Date: 2025-04-01 11:33:11.905282

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0c981dc7c9f7"
down_revision: Union[str, None] = "8e26edfca115"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("cards", "image_url", existing_type=sa.TEXT(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("cards", "image_url", existing_type=sa.TEXT(), nullable=False)
    # ### end Alembic commands ###
