"""remove legality field

Revision ID: 2fe4af6e587c
Revises: 484fc145faae
Create Date: 2025-04-02 10:17:58.382938

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "2fe4af6e587c"
down_revision: Union[str, None] = "484fc145faae"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("cards", "legality")
    op.drop_column("scryfall_cards", "legality")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "scryfall_cards",
        sa.Column(
            "legality",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "cards",
        sa.Column(
            "legality", postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=False
        ),
    )
    # ### end Alembic commands ###
