"""Add ScryfallCard model to database

Revision ID: 484fc145faae
Revises: 0c981dc7c9f7
Create Date: 2025-04-01 12:59:29.389718

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "484fc145faae"
down_revision: Union[str, None] = "0c981dc7c9f7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "scryfall_cards",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("scryfall_id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("set_name", sa.String(), nullable=False),
        sa.Column("image_url", sa.String(), nullable=True),
        sa.Column("mana_cost", sa.String(), nullable=True),
        sa.Column("mana_value", sa.Integer(), nullable=True),
        sa.Column("types", sa.JSON(), nullable=True),
        sa.Column("power", sa.String(), nullable=True),
        sa.Column("toughness", sa.String(), nullable=True),
        sa.Column("legality", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("scryfall_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("scryfall_cards")
    # ### end Alembic commands ###
